import { SLOT_HEIGHT_PX } from '@/Services/Scheduling/Scheduling.const';
import {
  CURRENT_TIME_BAR_COLOR,
  CURRENT_TIME_DOT_SIZE_PX,
  TODAY_BADGE_SIZE_PX,
  COLUMN_HEADER_HEIGHT_PX,
} from './ScheduleGrid.const';

export const styles = {
  weekRoot: {
    display: 'flex',
    alignItems: 'flex-start',
    backgroundColor: 'background.paper',
    overflow: 'auto',
    width: '100%',
    height: '100%',
    minHeight: 0,
    flex: 1,
    position: 'relative',
  },
  hourRail: {
    flex: '0 0 60px',
    borderRight: '1px solid',
    borderColor: 'divider',
    userSelect: 'none',
    minHeight: '100%',
    height: 'max-content',
  },
  hourRailSpacer: {
    height: COLUMN_HEADER_HEIGHT_PX,
    borderBottom: '1px solid',
    borderColor: 'divider',
    position: 'sticky',
    top: 0,
    bgcolor: 'background.paper',
    zIndex: 3,
  },
  hourLabel: {
    height: SLOT_HEIGHT_PX,
    fontSize: '0.75rem',
    fontWeight: 500,
    color: 'text.secondary',
    textAlign: 'right',
    pr: 1,
    pt: 0.25,
    boxSizing: 'border-box',
    transform: 'translateY(-0.6em)',
  },
  column: {
    flex: 1,
    minWidth: 120,
    borderRight: '1px solid',
    borderColor: 'divider',
    position: 'relative',
    minHeight: '100%',
    height: 'max-content',
  },
  columnHeader: (isToday: boolean) => ({
    height: COLUMN_HEADER_HEIGHT_PX,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.5,
    borderBottom: '1px solid',
    borderColor: 'divider',
    position: 'sticky',
    top: 0,
    bgcolor: 'background.paper',
    zIndex: 2,
    color: isToday ? 'primary.main' : 'text.secondary',
  }),
  headerWeekday: {
    fontSize: '0.7rem',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    lineHeight: 1,
  },
  headerDayNumber: (isToday: boolean) => ({
    width: TODAY_BADGE_SIZE_PX,
    height: TODAY_BADGE_SIZE_PX,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.95rem',
    fontWeight: isToday ? 700 : 500,
    lineHeight: 1,
    backgroundColor: isToday ? 'primary.main' : 'transparent',
    color: isToday ? 'primary.contrastText' : 'text.primary',
    transition: 'background-color 150ms ease, color 150ms ease',
  }),
  columnBody: (heightPx: number) => ({
    position: 'relative',
    height: heightPx,
  }),
  slotLine: (interactive: boolean) => ({
    height: SLOT_HEIGHT_PX,
    borderBottom: '1px dashed',
    borderColor: 'divider',
    boxSizing: 'border-box',
    ...(interactive && {
      transition: 'background-color 150ms ease',
      '&:hover': {
        backgroundColor: 'action.hover',
        cursor: 'pointer',
      },
    }),
  }),
  eventLayer: (topPx: number, heightPx: number) => ({
    position: 'absolute',
    top: topPx,
    left: 2,
    right: 2,
    height: heightPx,
    zIndex: 1,
  }),
  currentTimeLine: (topPx: number) => ({
    position: 'absolute',
    top: topPx,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: CURRENT_TIME_BAR_COLOR,
    zIndex: 2,
    pointerEvents: 'none',
  }),
  currentTimeDot: {
    position: 'absolute',
    top: -(CURRENT_TIME_DOT_SIZE_PX / 2) + 1,
    left: -(CURRENT_TIME_DOT_SIZE_PX / 2),
    width: CURRENT_TIME_DOT_SIZE_PX,
    height: CURRENT_TIME_DOT_SIZE_PX,
    borderRadius: '50%',
    backgroundColor: CURRENT_TIME_BAR_COLOR,
  },
  agendaRoot: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    p: 1.5,
    flex: 1,
    minHeight: 0,
    overflow: 'auto',
  },
  agendaDay: {
    fontSize: '0.85rem',
    fontWeight: 700,
    color: 'text.secondary',
    mb: 1,
    textTransform: 'capitalize',
  },
  agendaDayList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
} as const;
