export const widgetStyles = {
  container: {
    position: 'fixed',
    bottom: 24,
    right: 24,
    zIndex: 1300,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 2,
  },
  panel: {
    width: 360,
    height: 500,
    maxHeight: 'calc(100vh - 100px)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxShadow: 3,
    borderRadius: 2,
    bgcolor: 'background.paper',
  },
  header: {
    p: 2,
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    borderBottom: '1px solid',
    borderColor: 'divider',
    bgcolor: 'primary.main',
    color: 'primary.contrastText',
  },
  messagesArea: {
    flex: 1,
    p: 2,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    bgcolor: 'grey.50',
  },
  inputArea: {
    p: 2,
    borderTop: '1px solid',
    borderColor: 'divider',
    bgcolor: 'background.paper',
  },
  messageBubble: (isOwn: boolean) => ({
    maxWidth: '85%',
    p: 1.5,
    borderRadius: 2,
    alignSelf: isOwn ? 'flex-end' : 'flex-start',
    bgcolor: isOwn ? 'primary.main' : 'background.paper',
    color: isOwn ? 'primary.contrastText' : 'text.primary',
    boxShadow: 1,
    borderTopRightRadius: isOwn ? 0 : undefined,
    borderTopLeftRadius: isOwn ? undefined : 0,
  }),
};
