import { GlobalStyles } from '@mui/material';

export default function AppGlobalStyles() {
  return (
    <GlobalStyles
      styles={{
        ':root': {
          '--app-background': '#f7f5ef',
          '--app-surface': '#fffdf9',
          '--app-surface-strong': '#ffffff',
          '--app-surface-subtle': '#f4f1e9',
          '--app-surface-muted': '#ece8de',
          '--app-text': '#1d2530',
          '--app-text-muted': '#5b6470',
          '--app-text-subtle': '#7d857f',
          '--app-primary': '#2859d8',
          '--app-primary-strong': '#1942b5',
          '--app-primary-soft': '#e9efff',
          '--app-primary-soft-strong': '#dde6ff',
          '--app-success': '#3f7650',
          '--app-warning': '#a56c1d',
          '--app-danger': '#b44444',
          '--app-border': 'rgba(29, 37, 48, 0.10)',
          '--app-border-strong': 'rgba(29, 37, 48, 0.20)',
          '--app-focus': 'rgba(40, 89, 216, 0.32)',
          '--app-shadow-sm': '0 8px 22px rgba(39, 45, 53, 0.06)',
          '--app-shadow-md': '0 18px 46px rgba(39, 45, 53, 0.09)',
          '--bg': 'var(--app-background)',
          '--text': 'var(--app-text)',
          '--muted-text': 'var(--app-text-muted)',
          '--alt-text': '#ffffff',
          '--accent': 'var(--app-primary)',
          '--secondary': '#58705c',
          '--success': 'var(--app-success)',
          '--danger': 'var(--app-danger)',
          '--border': 'var(--app-border)',
          '--selected': 'var(--app-primary-soft)',
          '--glass-bg-strong': 'rgba(255, 255, 255, 0.7)',
          '--glass-border-strong': 'rgba(27, 31, 42, 0.08)',
          '--blur-amount': '16px',
          '--landing-gradient': 'radial-gradient(circle at 15% 20%, rgba(73, 104, 242, 0.18), transparent 55%), radial-gradient(circle at 85% 10%, rgba(107, 92, 255, 0.16), transparent 45%), #f7f8fb',
          '--landing-dots-color': 'rgba(27, 31, 42, 0.16)',
          '--landing-dots-dot-size': '1px',
          '--landing-dots-fade-size': '1.2px',
          '--landing-dots-gap': '34px',
          '--landing-dots-opacity': '0.5',
          '--landing-nav-bg': 'rgba(255, 255, 255, 0.7)',
          '--landing-nav-shadow': '0 16px 40px rgba(27, 31, 42, 0.12)',
          '--landing-nav-sheen': 'linear-gradient(120deg, rgba(255, 255, 255, 0.8) 0%, transparent 60%)',
          '--landing-nav-sheen-opacity': '0.35',
          '--landing-nav-blend-mode': 'screen',
          '--cta-shadow': '0 16px 40px rgba(73, 104, 242, 0.22)',
          '--cta-shadow-hover': '0 18px 46px rgba(73, 104, 242, 0.3)',
          '--cta-focus-outline': 'rgba(73, 104, 242, 0.55)',
          '--nav-login-shadow': '0 14px 30px rgba(73, 104, 242, 0.22)',
          '--nav-login-shadow-hover': '0 18px 46px rgba(73, 104, 242, 0.3)',
          '--nav-login-outline': 'rgba(73, 104, 242, 0.55)',
          '--section-kicker-bg': 'rgba(73, 104, 242, 0.12)',
          '--landing-faq-panel-bg': 'rgba(255, 255, 255, 0.8)',
          '--landing-faq-panel-shadow': '0 18px 48px rgba(27, 31, 42, 0.14)',
          '--landing-faq-item-bg': 'rgba(255, 255, 255, 0.9)',
          '--landing-faq-item-shadow': '0 14px 30px rgba(27, 31, 42, 0.12)',
          '--landing-faq-item-shadow-hover': '0 20px 40px rgba(27, 31, 42, 0.18)',
          '--landing-faq-accent-gradient': 'linear-gradient(135deg, rgba(73, 104, 242, 0.22), rgba(107, 92, 255, 0.16))',
          '--landing-faq-open-border': 'rgba(73, 104, 242, 0.4)',
          '--landing-faq-bar-gradient': 'linear-gradient(180deg, rgba(73, 104, 242, 0.8), rgba(107, 92, 255, 0.5))',
          '--landing-faq-bar-shadow': '0 0 10px rgba(73, 104, 242, 0.25)',
          '--landing-faq-bar-gradient-open': 'linear-gradient(180deg, rgba(73, 104, 242, 0.9), rgba(107, 92, 255, 0.65))',
          '--landing-faq-bar-shadow-open': '0 0 14px rgba(73, 104, 242, 0.35)',
          '--landing-faq-chevron-bg': 'rgba(73, 104, 242, 0.1)',
          '--landing-faq-chevron-bg-open': 'rgba(73, 104, 242, 0.18)',
          '--landing-faq-divider': 'rgba(27, 31, 42, 0.08)',
          '--feature-card-shadow': '0 18px 36px rgba(27, 31, 42, 0.12)',
          '--feature-card-shadow-hover': '0 24px 48px rgba(27, 31, 42, 0.18)',
          '--carousel-control-shadow': '0 12px 24px rgba(27, 31, 42, 0.12)',
          '--carousel-control-shadow-hover': '0 16px 32px rgba(27, 31, 42, 0.18)',
          '--carousel-control-border-hover': 'rgba(73, 104, 242, 0.3)',
          '--carousel-control-outline': 'rgba(73, 104, 242, 0.5)',
          '--feature-card-bg-cloud': 'rgba(73, 104, 242, 0.15)',
          '--feature-card-bg-analytics': 'rgba(107, 92, 255, 0.14)',
          '--feature-card-bg-lessons': 'rgba(46, 125, 50, 0.12)',
          '--feature-card-bg-meetings': 'rgba(211, 47, 47, 0.12)',
          '--footer-separator': 'rgba(27, 31, 42, 0.08)',
          '--admin-bg': 'var(--app-background)',
          '--admin-surface': 'var(--app-surface)',
          '--admin-surface-low': 'var(--app-surface-subtle)',
          '--admin-surface-container': 'var(--app-surface-muted)',
          '--admin-surface-high': '#e4e0d6',
          '--admin-text': 'var(--app-text)',
          '--admin-muted': 'var(--app-text-muted)',
          '--admin-border': 'var(--app-border)',
          '--admin-outline': 'var(--app-border-strong)',
          '--admin-primary': 'var(--app-primary)',
          '--admin-primary-soft': '#8ba5ef',
          '--admin-secondary': 'var(--app-success)',
          '--admin-secondary-soft': '#c5edc7',
          '--admin-danger': '#a8364b',
          '--admin-success': '#3f7f50',
          '--admin-warning': '#766b2f',
          '--admin-shadow': '0 20px 40px rgba(48, 51, 48, 0.05)',
        },
        body: {
          margin: 0,
          background: 'var(--bg)',
          color: 'var(--text)',
          fontFamily: "'Manrope', 'Inter', sans-serif",
          WebkitFontSmoothing: 'antialiased',
        },
        '*, *::before, *::after': {
          boxSizing: 'border-box',
        },
        '::selection': {
          backgroundColor: 'var(--app-primary-soft-strong)',
          color: 'var(--app-text)',
        },
        'button, input, textarea, select': {
          font: 'inherit',
        },
        '#root': {
          minHeight: '100vh',
        },
        '.material-symbols-outlined': {
          fontFamily: '"Material Symbols Outlined"',
          fontWeight: 400,
          fontStyle: 'normal',
          fontSize: '22px',
          lineHeight: 1,
          letterSpacing: 'normal',
          textTransform: 'none',
          display: 'inline-block',
          whiteSpace: 'nowrap',
          wordWrap: 'normal',
          direction: 'ltr',
          fontFeatureSettings: '"liga"',
          WebkitFontSmoothing: 'antialiased',
          fontVariationSettings: '"FILL" 0, "wght" 350, "GRAD" 0, "opsz" 24',
        },
        '@media (prefers-reduced-motion: reduce)': {
          '*, *::before, *::after': {
            scrollBehavior: 'auto !important',
            animationDuration: '0.01ms !important',
            animationIterationCount: '1 !important',
            transitionDuration: '0.01ms !important',
          },
        },
      }}
    />
  );
}
